#spring.application.name=demo
#server.port=8888
#
#
#spring.messages.basename=message/messages,message/common,message/member
#spring.messages.encoding=UTF-8
#spring.messages.fallbackToSystemLocale=false
#spring.messages.alwaysUseMessageFormat=true


server:
  port: 8888

spring:
  application:
    name: demo
  messages:
    basename: i18n/messages, i18n/common, i18n/member
    encoding: UTF-8
    # 언어별 message 파일을 찾지 못한 경우에 대한 설정 (default true)
    # true → 시스템 설정 (MessageConfig)에서 설정한 언어에 맞는 message 파일 활용
    # false → default 파일 (message.properties) 활용
    fallbackToSystemLocale: false
    # messageFormat 항상 사용 여부 (arguments에 따른 format 처리 방식) (default false)
    # true → 항상 사용
    ## 예를 들어 message.properties에 welcome=Hello ''라고 되어있는걸 호출하면 Hello '로 출력
    ## 예를 들어 message.properties에 welcome=Hello ''{0} 라고 되어있는걸 호출하면 Hello '{0}로 출력
    # false → 항상 미사용
    ## 예를 들어 message.properties에 welcome=Hello ''라고 되어있는걸 호출하면 Hello ''로 출력
    ## 예를 들어 message.properties에 welcome=Hello ''{0} 라고 되어있는걸 호출하면 Hello '{0}로 출력
    alwaysUseMessageFormat: true
    # 메세지 코드를 찾지 못했을 때 메세지 코드를 그대로 반환하는 설정 (default false)
    # true → 코드 값 그대로 반환
    # false → exception 발생
    useCodeAsDefaultMessage: false